apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: python-custom-autoscaler
spec:
  template:
    spec:
      containers:
      - name: python-custom-autoscaler
        image: carlito9675/python-custom-autoscaler:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-target
  config:
    - name: interval
      value: "10000"