extraScrapeConfigs: |
  - job_name: opencost
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['opencost.default.svc.cluster.local:9003']
  - job_name: app-service
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['app-service.default.svc.cluster.local:90']
  - job_name: locust-exporter
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['locust-exporter.default.svc.cluster.local:9646']