# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kubernetes-autoscaler
#   labels:
#     numPods: "3"
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kubernetes-autoscaler
#   template:
#     metadata:
#       labels:
#         app: kubernetes-autoscaler
#     spec:
#       containers:
#       - name: kubernetes-autoscaler
#         image: carlito9675/python-custom-autoscaler:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-target
  namespace: default
  labels:
    app: test-target
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-target
  template:
    metadata:
      labels:
        app: test-target
    spec:
      containers:
      - name: test-target
        image: carlito9675/test-target:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 
