apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment
  labels:
    app: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: carlito9675/locust:latest
        ports:
        - containerPort: 8089

