apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-exporter
  labels:
    app: locust-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-exporter
  template:
    metadata:
      labels:
        app: locust-exporter
    spec:
      containers:
      - name: exporter
        image: ghcr.io/anas-aso/locust_exporter:latest
        args:
          - "--locust.uri"
          - "http://locust-service.default.svc.cluster.local:8089"
        ports:
        - containerPort: 9646
