apiVersion: v1
kind: Service
metadata:
  name: locust-exporter
  labels:
    app: locust-exporter
spec:
  selector:
    app: locust-exporter
  ports:
    - protocol: TCP
      port: 9646
      targetPort: 9646
