apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
  labels:
    app: app-target
spec:
  selector:
    app: app-target
  ports:
    - protocol: TCP
      port: 90
      targetPort: 8090
      name: http
  type: ClusterIP
