apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-target
  namespace: default
  labels:
    app: app-target
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-target
  template:
    metadata:
      labels:
        app: app-target
    spec:
      containers:
      - name: app-target
        image: carlito9675/app-target:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
